// ============================================================
// DO NOT EDIT — generated by tui/scripts/gen-ipc-types.ts
// Source of truth: src/kosmos/ipc/frame_schema.py (Pydantic v2)
// FR-003: TypeScript types are derived from Pydantic models.
// Regenerate: bun run gen:ipc
// Drift check: bun run gen:ipc -- --check
// ============================================================

/* eslint-disable */
// @ts-nocheck

export type IPCFrame =
  | UserInputFrame
  | ChatRequestFrame
  | AssistantChunkFrame
  | ToolCallFrame
  | ToolResultFrame
  | CoordinatorPhaseFrame
  | WorkerStatusFrame
  | PermissionRequestFrame
  | PermissionResponseFrame
  | SessionEventFrame
  | ErrorFrame
  | PayloadStartFrame
  | PayloadDeltaFrame
  | PayloadEndFrame
  | BackpressureSignalFrame
  | ResumeRequestFrame
  | ResumeResponseFrame
  | ResumeRejectedFrame
  | HeartbeatFrame
  | NotificationPushFrame
  | PluginOpFrame
  | AdapterManifestSyncFrame
  | ConsentRevokeRequestFrame
  | ConsentRevokeResponseFrame;
/**
 * Opaque session identifier.
 */
export type SessionId = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId = string | null;
/**
 * True when this frame terminates a logical payload/stream.
 */
export type Final = boolean;
/**
 * Mirror of envelope transaction_id for trailer-only consumers. Non-empty when present (parity with codec.ts trailer schema — Spec 2642 § US3).
 */
export type TransactionId1 = string | null;
/**
 * Hex SHA-256 of the concatenated payload bytes for streamed payloads.
 */
export type ChecksumSha256 = string | null;
/**
 * Frame discriminator.
 */
export type Kind = 'user_input';
/**
 * Raw user text in UTF-8 (may contain Korean, English, emoji).
 */
export type Text = string;
/**
 * Opaque session identifier.
 */
export type SessionId1 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId1 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts1 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version1 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role1 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq1 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId2 = string | null;
/**
 * Frame discriminator.
 */
export type Kind1 = 'chat_request';
/**
 * Conversation history; tail message has role 'user' or 'tool'.
 *
 * @minItems 1
 */
export type Messages = [ChatMessage, ...ChatMessage[]];
/**
 * Conversation turn author.
 */
export type Role2 = 'system' | 'user' | 'assistant' | 'tool';
/**
 * UTF-8 message body.
 */
export type Content = string;
/**
 * Tool name when role='tool'; None otherwise.
 */
export type Name = string | null;
/**
 * Matching ``ToolCallFrame.call_id`` when role='tool'; None otherwise.
 */
export type ToolCallId = string | null;
/**
 * OpenAI Chat Completions assistant-turn tool invocations. Set ONLY on role='assistant' messages that requested one or more tool calls. None for every other role. Each entry's ``id`` is the pairing key that the corresponding role='tool' result message MUST set as its ``tool_call_id``.
 */
export type ToolCalls = ChatMessageToolCall[] | null;
/**
 * Matching ``ToolCallFrame.call_id`` / ``role='tool'.tool_call_id``.
 */
export type Id = string;
/**
 * OpenAI tool envelope; only 'function' is currently supported.
 */
export type Type = 'function';
/**
 * Function/tool name the model requested.
 */
export type Name1 = string;
/**
 * JSON-serialised string of the function arguments (OpenAI spec).
 */
export type Arguments = string;
/**
 * OpenAI tool envelope; only 'function' is currently supported.
 */
export type Type1 = 'function';
/**
 * Tool name (matches the primitive registry id).
 */
export type Name2 = string;
/**
 * Human-readable description shown to the model for tool selection.
 */
export type Description = string | null;
/**
 * Tools available to the model this turn.
 */
export type Tools = ToolDefinition[];
/**
 * Effective system prompt (may be None if backend supplies its own).
 */
export type System = string | null;
/**
 * Maximum tokens for the assistant turn.
 */
export type MaxTokens = number;
/**
 * Sampling temperature.
 */
export type Temperature = number;
/**
 * Nucleus sampling threshold.
 */
export type TopP = number;
/**
 * Opaque session identifier.
 */
export type SessionId2 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId2 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts2 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version2 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role3 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq2 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId3 = string | null;
/**
 * Frame discriminator.
 */
export type Kind2 = 'assistant_chunk';
/**
 * ULID of the assistant message this delta belongs to.
 */
export type MessageId = string;
/**
 * UTF-8 text appended to the visible answer (text_delta channel).
 */
export type Delta = string;
/**
 * UTF-8 text appended to the model's chain-of-thought (thinking_delta channel — K-EXAONE delta.reasoning_content).
 */
export type Thinking = string;
/**
 * True if this is the terminal chunk for this message_id.
 */
export type Done = boolean;
/**
 * Opaque session identifier.
 */
export type SessionId3 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId3 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts3 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version3 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role4 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq3 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId4 = string | null;
/**
 * Frame discriminator.
 */
export type Kind3 = 'tool_call';
/**
 * ULID correlating this call to its subsequent tool_result.
 */
export type CallId = string;
/**
 * Primitive name per Spec 031.
 */
export type Name3 = 'lookup' | 'resolve_location' | 'submit' | 'verify';
/**
 * Opaque session identifier.
 */
export type SessionId4 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId4 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts4 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version4 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role5 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq4 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId5 = string | null;
/**
 * Frame discriminator.
 */
export type Kind4 = 'tool_result';
/**
 * ULID correlating this result to its originating tool_call.
 */
export type CallId1 = string;
/**
 * Primitive kind discriminator per Spec 031.
 */
export type Kind5 = 'lookup' | 'resolve_location' | 'submit' | 'verify';
/**
 * Opaque session identifier.
 */
export type SessionId5 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId5 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts5 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version5 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role6 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq5 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId6 = string | null;
/**
 * Frame discriminator.
 */
export type Kind6 = 'coordinator_phase';
/**
 * Current coordinator phase.
 */
export type Phase = 'Research' | 'Synthesis' | 'Implementation' | 'Verification';
/**
 * Opaque session identifier.
 */
export type SessionId6 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId6 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts6 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version6 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role7 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq6 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId7 = string | null;
/**
 * Frame discriminator.
 */
export type Kind7 = 'worker_status';
/**
 * Unique worker identifier.
 */
export type WorkerId = string;
/**
 * Specialist label (e.g., transport-specialist, health-specialist).
 */
export type RoleId = string;
/**
 * Primitive currently being invoked by this worker.
 */
export type CurrentPrimitive = 'lookup' | 'resolve_location' | 'submit' | 'verify';
/**
 * Worker execution status.
 */
export type Status = 'idle' | 'running' | 'waiting_permission' | 'error';
/**
 * Opaque session identifier.
 */
export type SessionId7 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId7 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts7 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version7 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role8 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq7 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId8 = string | null;
/**
 * Frame discriminator.
 */
export type Kind8 = 'permission_request';
/**
 * ULID; round-trips in the matching permission_response frame.
 */
export type RequestId = string;
/**
 * Worker requesting permission.
 */
export type WorkerId1 = string;
/**
 * The primitive the worker wants to invoke.
 */
export type PrimitiveKind = 'lookup' | 'resolve_location' | 'submit' | 'verify';
/**
 * Korean-language description shown to the citizen.
 */
export type DescriptionKo = string;
/**
 * English-language description shown alongside the Korean one.
 */
export type DescriptionEn = string;
/**
 * Risk classification of the requested operation.
 */
export type RiskLevel = 'low' | 'medium' | 'high';
/**
 * Fully-qualified adapter id (e.g. `mock_verify_mobile_id`). Falls back to worker_id || primitive_kind in the TUI when None. None for legacy callers that have not yet been updated.
 */
export type ToolId = string | null;
/**
 * Opaque session identifier.
 */
export type SessionId8 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId8 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts8 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version8 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role9 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq8 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId9 = string | null;
/**
 * Frame discriminator.
 */
export type Kind9 = 'permission_response';
/**
 * ULID matching the originating permission_request.request_id.
 */
export type RequestId1 = string;
/**
 * Citizen's permission decision.
 */
export type Decision = 'granted' | 'allow_once' | 'allow_session' | 'denied' | 'deny';
/**
 * Consent receipt UUID written to ~/.kosmos/memdir/user/consent/<id>.json on granted decisions. None on deny / timeout.
 */
export type ReceiptId = string | null;
/**
 * The primitive that was authorised. The TUI feeds this into `aalToLayer(primitive, isIrreversible)` to recompute the gauntlet layer (1=green / 2=orange / 3=red) for the receipt row. None on deny / timeout / legacy backends.
 */
export type PrimitiveKind1 = ('lookup' | 'resolve_location' | 'submit' | 'verify') | null;
/**
 * The fully-qualified adapter id (e.g. `mock_verify_mobile_id`, `mock_submit_welfare_grant`) the citizen authorised. The TUI uses this to render the human-readable Korean adapter name in /consent list and the modal title. None for non-adapter primitives (rare) or legacy backends.
 */
export type ToolId1 = string | null;
/**
 * Opaque session identifier.
 */
export type SessionId9 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId9 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts9 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version9 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role10 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq9 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId10 = string | null;
/**
 * Frame discriminator.
 */
export type Kind10 = 'session_event';
/**
 * Session lifecycle event type.
 */
export type Event = 'save' | 'load' | 'list' | 'resume' | 'new' | 'exit';
/**
 * Opaque session identifier.
 */
export type SessionId10 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId10 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts10 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version10 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role11 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq10 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId11 = string | null;
/**
 * Frame discriminator.
 */
export type Kind11 = 'error';
/**
 * Machine-readable error code (e.g., 'backend_crash', 'protocol_mismatch').
 */
export type Code = string;
/**
 * Human-readable short message. MUST NOT contain KOSMOS_*-prefixed env var values (FR-004 redaction rule).
 */
export type Message = string;
/**
 * Opaque session identifier.
 */
export type SessionId11 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId11 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts11 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version11 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role12 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq11 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId12 = string | null;
/**
 * Frame discriminator.
 */
export type Kind12 = 'payload_start';
/**
 * Payload MIME type.
 */
export type ContentType = 'text/markdown' | 'application/json' | 'text/plain';
/**
 * Optional size hint for HUD progress bars.
 */
export type EstimatedBytes = number | null;
/**
 * Opaque session identifier.
 */
export type SessionId12 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId12 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts12 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version12 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role13 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq12 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId13 = string | null;
/**
 * Frame discriminator.
 */
export type Kind13 = 'payload_delta';
/**
 * Monotonic within the payload (first delta = 0).
 */
export type DeltaSeq = number;
/**
 * UTF-8 text. If content-type is application/json, this is a JSON-encoded fragment string.
 */
export type Payload1 = string;
/**
 * Opaque session identifier.
 */
export type SessionId13 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId13 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts13 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version13 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role14 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq13 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId14 = string | null;
/**
 * Frame discriminator.
 */
export type Kind14 = 'payload_end';
/**
 * Total number of payload_delta frames emitted.
 */
export type DeltaCount = number;
/**
 * Terminal disposition.
 */
export type Status1 = 'ok' | 'aborted';
/**
 * Opaque session identifier.
 */
export type SessionId14 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId14 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts14 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version14 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role15 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq14 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId15 = string | null;
/**
 * Frame discriminator.
 */
export type Kind15 = 'backpressure';
/**
 * Reader action. pause=stop emitting; resume=clear; throttle=slow down.
 */
export type Signal = 'pause' | 'resume' | 'throttle';
/**
 * Origin of the signal.
 */
export type Source = 'tui_reader' | 'backend_writer' | 'upstream_429';
/**
 * Current outbound queue size.
 */
export type QueueDepth = number;
/**
 * High-water mark threshold in effect (default 64).
 */
export type Hwm = number;
/**
 * For throttle sourced from upstream_429; reflects Retry-After. ge=0.
 */
export type RetryAfterMs = number | null;
/**
 * Korean HUD copy (civic-facing). Must be non-empty (FR-015).
 */
export type HudCopyKo = string;
/**
 * English HUD copy (dev-facing). Must be non-empty (FR-015).
 */
export type HudCopyEn = string;
/**
 * Opaque session identifier.
 */
export type SessionId15 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId15 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts15 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version15 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role16 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq15 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId16 = string | null;
/**
 * Frame discriminator.
 */
export type Kind16 = 'resume_request';
/**
 * Last correlation_id the TUI successfully applied. None if no prior frame.
 */
export type LastSeenCorrelationId = string | null;
/**
 * Last frame_seq applied. None if none.
 */
export type LastSeenFrameSeq = number | null;
/**
 * TUI-local session token for authenticity binding.
 */
export type TuiSessionToken = string;
/**
 * Opaque session identifier.
 */
export type SessionId16 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId16 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts16 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version16 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role17 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq16 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId17 = string | null;
/**
 * Frame discriminator.
 */
export type Kind17 = 'resume_response';
/**
 * Inclusive lower bound of frames that will be replayed.
 */
export type ResumedFromFrameSeq = number;
/**
 * Total frames the backend will replay. Bounded by ring buffer size.
 */
export type ReplayCount = number;
/**
 * Backend-assigned session id the TUI should use going forward.
 */
export type ServerSessionId = string;
/**
 * Negotiated heartbeat cadence (default 30000).
 */
export type HeartbeatIntervalMs = number;
/**
 * Opaque session identifier.
 */
export type SessionId17 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId17 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts17 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version17 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role18 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq17 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId18 = string | null;
/**
 * Frame discriminator.
 */
export type Kind18 = 'resume_rejected';
/**
 * Machine-readable reason code.
 */
export type Reason =
  | 'ring_evicted'
  | 'session_unknown'
  | 'token_mismatch'
  | 'protocol_incompatible'
  | 'session_expired';
/**
 * Human-readable Korean/English detail for HUD.
 */
export type Detail = string;
/**
 * Opaque session identifier.
 */
export type SessionId18 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId18 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts18 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version18 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role19 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq18 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId19 = string | null;
/**
 * Frame discriminator.
 */
export type Kind19 = 'heartbeat';
/**
 * ping from sender, pong from receiver.
 */
export type Direction = 'ping' | 'pong';
/**
 * Sender's current outbound frame_seq high-water.
 */
export type PeerFrameSeq = number;
/**
 * Opaque session identifier.
 */
export type SessionId19 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId19 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts19 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version19 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role20 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq19 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId20 = string | null;
/**
 * Frame discriminator.
 */
export type Kind20 = 'notification_push';
/**
 * Notification channel handle.
 */
export type SubscriptionId = string;
/**
 * e.g., disaster_alert_cbs_push, gov_newsroom_push.
 */
export type AdapterId = string;
/**
 * RSS guid or CBS event hash for duplicate suppression.
 */
export type EventGuid = string;
/**
 * Inline payload MIME.
 */
export type PayloadContentType = 'text/plain' | 'application/json';
/**
 * Inline notification content (Korean for civic users).
 */
export type Payload2 = string;
/**
 * Opaque session identifier.
 */
export type SessionId20 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId20 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts20 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version20 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role21 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq20 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId21 = string | null;
/**
 * Frame discriminator.
 */
export type Kind21 = 'plugin_op';
/**
 * Operation phase. ``request`` = TUI initiates install/uninstall/list; ``progress`` = backend reports phase tick; ``complete`` = backend reports terminal outcome.
 */
export type Op = 'request' | 'progress' | 'complete';
/**
 * Sub-action when op='request'. Required for op='request'; None otherwise.
 */
export type RequestOp = ('install' | 'uninstall' | 'list') | null;
/**
 * Plugin catalog name (matches CatalogEntry.name). Required when request_op in {install, uninstall}; None otherwise.
 */
export type Name4 = string | null;
/**
 * Optional SemVer pin for op='request'/install. Renamed from `version` to avoid shadowing the envelope's protocol version.
 */
export type RequestedVersion = string | null;
/**
 * When True, install verifies but writes nothing (op='request').
 */
export type DryRun = boolean | null;
/**
 * Install phase index 1-7 per contracts/plugin-install.cli.md. Required when op='progress'.
 */
export type ProgressPhase = number | null;
/**
 * Korean-primary progress message shown in the Ink overlay.
 */
export type ProgressMessageKo = string | null;
/**
 * English fallback progress message.
 */
export type ProgressMessageEn = string | null;
/**
 * Terminal outcome. Required when op='complete'.
 */
export type Result = ('success' | 'failure') | null;
/**
 * Process exit code per contracts/plugin-install.cli.md exit-code table. Required when op='complete'.
 */
export type ExitCode = number | null;
/**
 * Spec 035 consent receipt id when op='complete' AND result='success'.
 */
export type ReceiptId1 = string | null;
/**
 * Machine-readable failure kind (e.g. 'bundle_sha_mismatch', 'slsa_skip_in_production') when op='complete' AND result='failure'. Used by the TUI to map exit codes to citizen-friendly Korean messages.
 */
export type ErrorKind = string | null;
/**
 * Developer-facing English error detail when op='complete' AND result='failure'.
 */
export type ErrorMessage = string | null;
/**
 * True when op='complete' + result='success' but the operation was a no-op because the plugin was already in the target state (e.g. uninstall of a plugin that was never installed). TUI uses this to show '이미 제거됨' instead of '제거 완료'.
 */
export type WasIdempotentNoop = boolean | null;
/**
 * Opaque session identifier.
 */
export type SessionId21 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId21 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts21 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version21 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role22 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq21 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId22 = string | null;
/**
 * Frame discriminator — 21st arm of IPCFrame.
 */
export type Kind22 = 'adapter_manifest_sync';
/**
 * Full registry snapshot. Non-empty (I1); no duplicate tool_id (I2).
 *
 * @minItems 1
 */
export type Entries = [AdapterManifestEntry, ...AdapterManifestEntry[]];
/**
 * Globally unique adapter id within the registry, e.g. 'nmc_emergency_search'. Lowercase snake-case; validated by I7.
 */
export type ToolId2 = string;
/**
 * Human-readable display name; bilingual permitted.
 */
export type Name5 = string;
/**
 * Primitive verb the adapter is registered under (I6).
 */
export type Primitive = 'lookup' | 'submit' | 'verify' | 'resolve_location';
/**
 * Agency-published policy URL (HTTPS). None only when source_mode == 'internal' (I4/I5).
 */
export type PolicyAuthorityUrl = string | null;
/**
 * Tag for the citation-rendering surface.
 */
export type SourceMode = 'live' | 'mock' | 'internal';
/**
 * Lowercase hex SHA-256 of canonical-JSON-serialised entries sorted by tool_id (I3). Cheap change-detection for hot-reload (future epic).
 */
export type ManifestHash = string;
/**
 * Python backend PID at boot. Useful for OTEL span cross-correlation.
 */
export type EmitterPid = number;
/**
 * Opaque session identifier.
 */
export type SessionId22 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId22 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts22 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version22 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role23 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq22 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId23 = string | null;
/**
 * Frame discriminator — arm 22 of IPCFrame.
 */
export type Kind23 = 'consent_revoke_request';
/**
 * UUIDv4 round-trip correlation ID; matched in consent_revoke_response.
 */
export type RequestId2 = string;
/**
 * Target receipt identifier (rcpt-<id>). Must match an existing receipt file at ~/.kosmos/memdir/user/consent/<receipt_id>.json.
 */
export type ReceiptId2 = string;
/**
 * Revocation scope. 'once' revokes only this receipt; 'session-all' revokes all receipts in the current session.
 */
export type Scope = 'once' | 'session-all';
/**
 * Optional citizen-provided reason logged to the ledger (PIPA §36 citation).
 */
export type Reason1 = string | null;
/**
 * Opaque session identifier.
 */
export type SessionId23 = string;
/**
 * UUIDv7 string for new emissions; ULID accepted for back-compat. Non-empty; emitter SHOULD use UUIDv7. (E5)
 */
export type CorrelationId23 = string;
/**
 * ISO-8601 UTC timestamp with sub-ms precision.
 */
export type Ts23 = string;
/**
 * Envelope version. Hard-fail on mismatch (E1, FR-001).
 */
export type Version23 = '1.0';
/**
 * Origin role. Validated against kind<->role allow-list (E3, FR-004).
 */
export type Role24 = 'tui' | 'backend' | 'tool' | 'llm' | 'notification';
/**
 * Per-session monotonic sequence number (ge=0). Gap detection uses this.
 */
export type FrameSeq23 = number;
/**
 * UUIDv7. Populated for idempotent state-change frames (irreversible tools). None for streaming chunks. (FR-026) Non-empty when present (parity with codec.ts ``z.string().min(1).nullable().optional()`` — Spec 2642 § US3).
 */
export type TransactionId24 = string | null;
/**
 * Frame discriminator — arm 23 of IPCFrame.
 */
export type Kind24 = 'consent_revoke_response';
/**
 * Mirrors consent_revoke_request.request_id for round-trip correlation.
 */
export type RequestId3 = string;
/**
 * True when at least one receipt was successfully revoked; False on error or not-found.
 */
export type Ok = boolean;
/**
 * ISO-8601 UTC timestamp of revocation. Populated when ok=True.
 */
export type RevokedAt = string | null;
/**
 * Hex SHA-256 of the ledger withdrawal record. Populated when ok=True for audit-chain verification.
 */
export type RecordHash = string | null;
/**
 * Machine-readable error code when ok=False; None on success.
 */
export type Error = ('already_revoked' | 'not_found' | 'io_error') | null;

/**
 * TUI -> backend: a citizen's typed input.
 */
export interface UserInputFrame {
  session_id: SessionId;
  correlation_id: CorrelationId;
  ts: Ts;
  version?: Version;
  role: Role;
  frame_seq?: FrameSeq;
  transaction_id?: TransactionId;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind;
  text: Text;
}
/**
 * Completion/validation metadata on terminal frames (FR-006).
 */
export interface FrameTrailer {
  final: Final;
  transaction_id?: TransactionId1;
  checksum_sha256?: ChecksumSha256;
}
/**
 * TUI -> backend: tools-aware chat request (Spec 1978 ADR-0001).
 *
 * Coexists with ``UserInputFrame`` (which remains the echo / smoke-test path).
 * The backend treats a ``UserInputFrame{text=t}`` as
 * ``ChatRequestFrame{messages=[{role:'user', content:t}], tools=[]}``.
 */
export interface ChatRequestFrame {
  session_id: SessionId1;
  correlation_id: CorrelationId1;
  ts: Ts1;
  version?: Version1;
  role: Role1;
  frame_seq?: FrameSeq1;
  transaction_id?: TransactionId2;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind1;
  messages: Messages;
  tools?: Tools;
  system?: System;
  max_tokens?: MaxTokens;
  temperature?: Temperature;
  top_p?: TopP;
}
/**
 * One conversation-history entry carried by ``ChatRequestFrame.messages``.
 *
 * ``role="tool"`` messages MUST also set ``name`` (the tool name that was
 * invoked) and ``tool_call_id`` (the originating ``tool_call`` envelope's
 * correlation id). This is the data-model invariant D4 (tool message
 * integrity) enforced by the ``ChatRequestFrame`` validator below.
 *
 * Lead-Diag-4 (2026-05-04): added optional ``tool_calls`` for ``role='assistant'``
 * turns so assistant ``tool_use`` blocks survive the wire round-trip and the
 * OpenAI Chat Completions multi-turn pairing invariant (every ``role='tool'``
 * message MUST follow an assistant message whose ``tool_calls[i].id`` matches
 * the result's ``tool_call_id``) is satisfied. Backward compatible: legacy
 * senders that omit ``tool_calls`` are unaffected.
 */
export interface ChatMessage {
  role: Role2;
  content: Content;
  name?: Name;
  tool_call_id?: ToolCallId;
  tool_calls?: ToolCalls;
}
/**
 * OpenAI-spec ``tool_calls[i]`` entry carried by an assistant ``ChatMessage``.
 *
 * OpenAI Chat Completions API spec: every ``role='tool'`` message MUST be
 * paired (by ``tool_call_id``) with a ``tool_calls[i].id`` from a preceding
 * assistant turn. The TUI carries this pairing across the wire so multi-turn
 * conversations replay correctly to FriendliAI / OpenAI-compatible providers
 * (Lead-Diag-4 fix, 2026-05-04).
 */
export interface ChatMessageToolCall {
  id: Id;
  type?: Type;
  function: ChatMessageFunctionCall;
}
/**
 * Inner function name + JSON-serialised arguments.
 */
export interface ChatMessageFunctionCall {
  name: Name1;
  arguments: Arguments;
}
/**
 * OpenAI-style tool definition (function-calling).
 */
export interface ToolDefinition {
  type?: Type1;
  function: ToolDefinitionFunction;
}
/**
 * Inner function metadata.
 */
export interface ToolDefinitionFunction {
  name: Name2;
  description?: Description;
  parameters?: Parameters;
}
/**
 * JSON Schema (Draft 2020-12) for the tool input. Pydantic accepts any dict shape; deeper schema validation is delegated to LLMClient.
 */
export interface Parameters {
  [k: string]: any;
}
/**
 * backend -> TUI: streaming assistant text delta.
 *
 * Mirrors Anthropic's ``content_block_delta`` (CC reference at
 * ``kosmos/llm/_cc_reference/claude.ts:2053-2169``). The ``delta`` field
 * carries the visible answer text (``text_delta`` in CC nomenclature);
 * ``thinking`` carries the model's chain-of-thought (``thinking_delta``
 * on the Anthropic side, K-EXAONE's ``delta.reasoning_content`` on the
 * OpenAI-compatible FriendliAI feed). Exactly one of ``delta`` /
 * ``thinking`` carries content per frame — the empty one is the
 * backward-compatible default. ``done`` terminates the message
 * regardless of channel.
 */
export interface AssistantChunkFrame {
  session_id: SessionId2;
  correlation_id: CorrelationId2;
  ts: Ts2;
  version?: Version2;
  role: Role3;
  frame_seq?: FrameSeq2;
  transaction_id?: TransactionId3;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind2;
  message_id: MessageId;
  delta?: Delta;
  thinking?: Thinking;
  done: Done;
}
/**
 * backend -> TUI (display only): a tool invocation decision by the model.
 */
export interface ToolCallFrame {
  session_id: SessionId3;
  correlation_id: CorrelationId3;
  ts: Ts3;
  version?: Version3;
  role: Role4;
  frame_seq?: FrameSeq3;
  transaction_id?: TransactionId4;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind3;
  call_id: CallId;
  name: Name3;
  arguments: Arguments1;
}
/**
 * Primitive-specific arguments; shape per Spec 031 input schemas.
 */
export interface Arguments1 {
  [k: string]: any;
}
/**
 * backend -> TUI (render): the output of a tool invocation.
 */
export interface ToolResultFrame {
  session_id: SessionId4;
  correlation_id: CorrelationId4;
  ts: Ts4;
  version?: Version4;
  role: Role5;
  frame_seq?: FrameSeq4;
  transaction_id?: TransactionId5;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind4;
  call_id: CallId1;
  envelope: ToolResultEnvelope;
}
/**
 * Active primitive discriminated union. Unknown kind falls to UnrecognizedPayload.
 */
export interface ToolResultEnvelope {
  kind: Kind5;
  [k: string]: any;
}
/**
 * backend -> TUI: Spec 027 coordinator phase update.
 */
export interface CoordinatorPhaseFrame {
  session_id: SessionId5;
  correlation_id: CorrelationId5;
  ts: Ts5;
  version?: Version5;
  role: Role6;
  frame_seq?: FrameSeq5;
  transaction_id?: TransactionId6;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind6;
  phase: Phase;
}
/**
 * backend -> TUI: per-worker status row update from Spec 027 swarm.
 */
export interface WorkerStatusFrame {
  session_id: SessionId6;
  correlation_id: CorrelationId6;
  ts: Ts6;
  version?: Version6;
  role: Role7;
  frame_seq?: FrameSeq6;
  transaction_id?: TransactionId7;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind7;
  worker_id: WorkerId;
  role_id: RoleId;
  current_primitive: CurrentPrimitive;
  status: Status;
}
/**
 * backend -> TUI: a worker raises a permission request.
 */
export interface PermissionRequestFrame {
  session_id: SessionId7;
  correlation_id: CorrelationId7;
  ts: Ts7;
  version?: Version7;
  role: Role8;
  frame_seq?: FrameSeq7;
  transaction_id?: TransactionId8;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind8;
  request_id: RequestId;
  worker_id: WorkerId1;
  primitive_kind: PrimitiveKind;
  description_ko: DescriptionKo;
  description_en: DescriptionEn;
  risk_level: RiskLevel;
  tool_id?: ToolId;
}
/**
 * TUI -> backend: citizen's decision on a permission_request.
 */
export interface PermissionResponseFrame {
  session_id: SessionId8;
  correlation_id: CorrelationId8;
  ts: Ts8;
  version?: Version8;
  role: Role9;
  frame_seq?: FrameSeq8;
  transaction_id?: TransactionId9;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind9;
  request_id: RequestId1;
  decision: Decision;
  receipt_id?: ReceiptId;
  primitive_kind?: PrimitiveKind1;
  tool_id?: ToolId1;
}
/**
 * Bidirectional: session lifecycle events.
 */
export interface SessionEventFrame {
  session_id: SessionId9;
  correlation_id: CorrelationId9;
  ts: Ts9;
  version?: Version9;
  role: Role10;
  frame_seq?: FrameSeq9;
  transaction_id?: TransactionId10;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind10;
  event: Event;
  payload: Payload;
}
/**
 * Event-specific payload. For list: {sessions: [{id, created_at, turn_count}]}. For resume: {id: str}. For others: {}.
 */
export interface Payload {
  [k: string]: any;
}
/**
 * backend -> TUI: a backend error surfaced to the TUI for rendering.
 */
export interface ErrorFrame {
  session_id: SessionId10;
  correlation_id: CorrelationId10;
  ts: Ts10;
  version?: Version10;
  role: Role11;
  frame_seq?: FrameSeq10;
  transaction_id?: TransactionId11;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind11;
  code: Code;
  message: Message;
  details: Details;
}
/**
 * Structured error details. KOSMOS_* env var values MUST be redacted.
 */
export interface Details {
  [k: string]: any;
}
/**
 * Begins a streamed payload (assistant output, tool result chunking).
 *
 * Sender MUST follow with >= 1 payload_delta and exactly one payload_end.
 * role allow-list: backend, tool, llm.
 */
export interface PayloadStartFrame {
  session_id: SessionId11;
  correlation_id: CorrelationId11;
  ts: Ts11;
  version?: Version11;
  role: Role12;
  frame_seq?: FrameSeq11;
  transaction_id?: TransactionId12;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind12;
  content_type: ContentType;
  estimated_bytes?: EstimatedBytes;
}
/**
 * One chunk of a streamed payload.
 *
 * role allow-list: backend, tool, llm.
 */
export interface PayloadDeltaFrame {
  session_id: SessionId12;
  correlation_id: CorrelationId12;
  ts: Ts12;
  version?: Version12;
  role: Role13;
  frame_seq?: FrameSeq12;
  transaction_id?: TransactionId13;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind13;
  delta_seq: DeltaSeq;
  payload: Payload1;
}
/**
 * Terminates a streamed payload.
 *
 * MUST carry a trailer with final=True.
 * role allow-list: backend, tool, llm.
 */
export interface PayloadEndFrame {
  session_id: SessionId13;
  correlation_id: CorrelationId13;
  ts: Ts13;
  version?: Version13;
  role: Role14;
  frame_seq?: FrameSeq13;
  transaction_id?: TransactionId14;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind14;
  delta_count: DeltaCount;
  status: Status1;
}
/**
 * Emitted when outgoing queue crosses HWM or a 429 condition is detected.
 *
 * role allow-list: tui (tui_reader), backend (backend_writer, upstream_429).
 * FR-012, FR-015: hud_copy_ko/en MUST be non-empty (min_length=1).
 */
export interface BackpressureSignalFrame {
  session_id: SessionId14;
  correlation_id: CorrelationId14;
  ts: Ts14;
  version?: Version14;
  role: Role15;
  frame_seq?: FrameSeq14;
  transaction_id?: TransactionId15;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind15;
  signal: Signal;
  source: Source;
  queue_depth: QueueDepth;
  hwm: Hwm;
  retry_after_ms?: RetryAfterMs;
  hud_copy_ko: HudCopyKo;
  hud_copy_en: HudCopyEn;
}
/**
 * Sent by the reconnecting TUI after a stdio drop.
 *
 * role allow-list: tui.
 */
export interface ResumeRequestFrame {
  session_id: SessionId15;
  correlation_id: CorrelationId15;
  ts: Ts15;
  version?: Version15;
  role: Role16;
  frame_seq?: FrameSeq15;
  transaction_id?: TransactionId16;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind16;
  last_seen_correlation_id?: LastSeenCorrelationId;
  last_seen_frame_seq?: LastSeenFrameSeq;
  tui_session_token: TuiSessionToken;
}
/**
 * Backend accepts the resume.
 *
 * Must be followed by replay of frames with frame_seq > last_seen_frame_seq.
 * Trailer with final=True MUST be set (E6).
 * role allow-list: backend.
 */
export interface ResumeResponseFrame {
  session_id: SessionId16;
  correlation_id: CorrelationId16;
  ts: Ts16;
  version?: Version16;
  role: Role17;
  frame_seq?: FrameSeq16;
  transaction_id?: TransactionId17;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind17;
  resumed_from_frame_seq: ResumedFromFrameSeq;
  replay_count: ReplayCount;
  server_session_id: ServerSessionId;
  heartbeat_interval_ms: HeartbeatIntervalMs;
}
/**
 * Backend cannot honor the resume request.
 *
 * Trailer with final=True MUST be set (E6).
 * role allow-list: backend.
 */
export interface ResumeRejectedFrame {
  session_id: SessionId17;
  correlation_id: CorrelationId17;
  ts: Ts17;
  version?: Version17;
  role: Role18;
  frame_seq?: FrameSeq17;
  transaction_id?: TransactionId18;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind18;
  reason: Reason;
  detail: Detail;
}
/**
 * Emitted every 30 s (default) by both sides to prove liveness.
 *
 * Note: Heartbeat frames do NOT increment frame_seq — they use a dedicated
 * counter. This keeps ring-buffer economy tight.
 * role allow-list: tui, backend.
 */
export interface HeartbeatFrame {
  session_id: SessionId18;
  correlation_id: CorrelationId18;
  ts: Ts18;
  version?: Version18;
  role: Role19;
  frame_seq?: FrameSeq18;
  transaction_id?: TransactionId19;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind19;
  direction: Direction;
  peer_frame_seq: PeerFrameSeq;
}
/**
 * Push from app/phone notification surfaces.
 *
 * Carried over the same stdio channel to keep a single correlation plane.
 * role allow-list: notification.
 *
 * CC parity: NO equivalent — Claude Code's notification surface is
 * terminal OSC sequences (iTerm2, Kitty, Ghostty, bell) emitted
 * in-process from ``ink/useTerminalNotification.ts``. There is no
 * push-based IPC notification arm in CC. KOSMOS adds this arm as a
 * swap-2 addition for Korean civic push channels (KMA disaster CBS,
 * government newsroom alerts, hospital alerts) carried over the
 * same stdio plane to keep a single correlation plane. Spec 2642
 * Epic F · S7 audit recorded this finding (specs/cc-migration-audit/
 * scope-S7-ipc-bridge.md § 5 Finding 3 — resolved as orthogonal
 * KOSMOS swap-2 add-on, not a CC-divergence regression).
 */
export interface NotificationPushFrame {
  session_id: SessionId19;
  correlation_id: CorrelationId19;
  ts: Ts19;
  version?: Version19;
  role: Role20;
  frame_seq?: FrameSeq19;
  transaction_id?: TransactionId20;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind20;
  subscription_id: SubscriptionId;
  adapter_id: AdapterId;
  event_guid: EventGuid;
  payload_content_type: PayloadContentType;
  payload: Payload2;
}
/**
 * Plugin install / uninstall / list control-plane frame.
 *
 * Single arm carrying the three operation states discriminated by the
 * inner ``op`` field. Modelled as one ``kind`` so the IPC discriminator
 * keeps ``plugin_op`` as a single 20th arm — matching the migration
 * tree's "20th arm" decision while preserving the per-phase shape
 * documented in ``contracts/plugin-install.cli.md``.
 *
 * Op-specific shape rules (enforced by ``_v_plugin_op_shape``):
 *
 * * ``op="request"``: ``name`` required when ``request_op`` is
 *   ``"install"`` or ``"uninstall"``; ``progress_phase`` /
 *   ``progress_message_ko`` / ``progress_message_en`` / ``result`` /
 *   ``exit_code`` MUST be ``None``.
 * * ``op="progress"``: ``progress_phase`` (1-7), ``progress_message_ko``,
 *   ``progress_message_en`` required; install-request fields must be
 *   ``None``.
 * * ``op="complete"``: ``result`` + ``exit_code`` required; everything
 *   else None except optional ``receipt_id``.
 *
 * role allow-list: tui (request), backend (progress / complete).
 */
export interface PluginOpFrame {
  session_id: SessionId20;
  correlation_id: CorrelationId20;
  ts: Ts20;
  version?: Version20;
  role: Role21;
  frame_seq?: FrameSeq20;
  transaction_id?: TransactionId21;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind21;
  op: Op;
  request_op?: RequestOp;
  name?: Name4;
  requested_version?: RequestedVersion;
  dry_run?: DryRun;
  progress_phase?: ProgressPhase;
  progress_message_ko?: ProgressMessageKo;
  progress_message_en?: ProgressMessageEn;
  result?: Result;
  exit_code?: ExitCode;
  receipt_id?: ReceiptId1;
  error_kind?: ErrorKind;
  error_message?: ErrorMessage;
  was_idempotent_noop?: WasIdempotentNoop;
}
/**
 * Full registry snapshot emitted by the backend exactly once after boot.
 *
 * 21st arm of the ``IPCFrame`` discriminated union (Epic ε #2296).
 *
 * Invariants enforced at construction:
 * - I1: ``entries`` is non-empty.
 * - I2: No two entries share the same ``tool_id``.
 * - I3: ``manifest_hash == sha256(canonical_json(sorted(entries, key=tool_id)))``.
 * - I4/I5/I6/I7: delegated to ``AdapterManifestEntry`` validators.
 *
 * On invariant violation the Pydantic validator raises ``ValueError``; the
 * backend boot should catch this and exit with ``SystemExit(78)`` per
 * Constitution § II + Spec 1634 boot-validation pattern.
 */
export interface AdapterManifestSyncFrame {
  session_id: SessionId21;
  correlation_id: CorrelationId21;
  ts: Ts21;
  version?: Version21;
  role: Role22;
  frame_seq?: FrameSeq21;
  transaction_id?: TransactionId22;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind22;
  entries: Entries;
  manifest_hash: ManifestHash;
  emitter_pid: EmitterPid;
}
/**
 * One adapter record inside an ``AdapterManifestSyncFrame.entries`` array.
 *
 * Used by the TS-side cache to resolve ``tool_id`` and populate the citation
 * slot in permission prompts.
 *
 * Validators:
 * - ``policy_authority_url`` required (HTTPS) when ``source_mode`` is ``"live"``
 *   or ``"mock"``; ``None`` only allowed when ``source_mode == "internal"`` (I4/I5).
 * - ``tool_id`` matches ``^[a-z][a-z0-9_]*$`` (I7).
 */
export interface AdapterManifestEntry {
  tool_id: ToolId2;
  name: Name5;
  primitive: Primitive;
  policy_authority_url?: PolicyAuthorityUrl;
  source_mode: SourceMode;
}
/**
 * TUI -> backend: citizen requests revocation of a prior consent receipt.
 *
 * arm 22 of the ``IPCFrame`` discriminated union (Epic 2).
 *
 * Fields:
 * - ``request_id``: UUIDv4 string; round-trips in the matching
 *   ``consent_revoke_response`` frame.
 * - ``receipt_id``: The ``rcpt-<id>`` value referencing the receipt file at
 *   ``~/.kosmos/memdir/user/consent/<receipt_id>.json``.
 * - ``scope``: ``"once"`` = revoke this single receipt only;
 *   ``"session-all"`` = revoke all receipts for the current session.
 * - ``reason``: Optional free-text reason logged to the audit ledger.
 *
 * role allow-list: tui.
 */
export interface ConsentRevokeRequestFrame {
  session_id: SessionId22;
  correlation_id: CorrelationId22;
  ts: Ts22;
  version?: Version22;
  role: Role23;
  frame_seq?: FrameSeq22;
  transaction_id?: TransactionId23;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind23;
  request_id: RequestId2;
  receipt_id: ReceiptId2;
  scope: Scope;
  reason?: Reason1;
}
/**
 * backend -> TUI: outcome of a consent_revoke_request.
 *
 * arm 23 of the ``IPCFrame`` discriminated union (Epic 2).
 *
 * Fields:
 * - ``request_id``: Mirrors the originating consent_revoke_request.request_id.
 * - ``ok``: True when at least one receipt was revoked; False on error or
 *   not-found.
 * - ``revoked_at``: ISO-8601 UTC timestamp of the revocation (when ok=True).
 * - ``record_hash``: Ledger entry SHA-256 for audit chain verification
 *   (when ok=True; omitted on error).
 * - ``error``: Machine-readable error code on failure (``already_revoked``,
 *   ``not_found``, ``io_error``); omitted on success.
 *
 * role allow-list: backend.
 */
export interface ConsentRevokeResponseFrame {
  session_id: SessionId23;
  correlation_id: CorrelationId23;
  ts: Ts23;
  version?: Version23;
  role: Role24;
  frame_seq?: FrameSeq23;
  transaction_id?: TransactionId24;
  /**
   * Completion/validation metadata. Populated on terminal frames. (FR-006)
   */
  trailer?: FrameTrailer | null;
  kind?: Kind24;
  request_id: RequestId3;
  ok: Ok;
  revoked_at?: RevokedAt;
  record_hash?: RecordHash;
  error?: Error;
}
