# SPDX-License-Identifier: Apache-2.0
"""KMA APIHub structured OpenAPI operation catalog."""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

type KmaApiHubScalar = str | int | float | bool | None
type KmaApiHubApprovalState = Literal["approved", "approval_pending"]


class KmaApiHubRequestParam(BaseModel):
    """Official request parameter metadata for one KMA APIHub operation."""

    model_config = ConfigDict(frozen=True)

    name: str
    field_name: str
    required: bool = True
    default: KmaApiHubScalar = None
    value_type: Literal["string", "integer", "number", "boolean"] = "string"
    is_credential: bool = False


class KmaApiHubOperation(BaseModel):
    """One structured ``typ02/openApi`` operation exposed by KMA APIHub."""

    model_config = ConfigDict(frozen=True)

    category_seq: int
    category_name_ko: str
    service: str
    operation: str
    tool_id: str
    endpoint_path: str
    request_params: tuple[KmaApiHubRequestParam, ...]
    approval_state: KmaApiHubApprovalState = "approval_pending"
    response_fields: tuple[str, ...] = Field(default_factory=tuple)

    @property
    def operation_id(self) -> str:
        """Return the stable APIHub ``<service>/<operation>`` identifier."""
        return f"{self.service}/{self.operation}"

    @property
    def non_credential_params(self) -> tuple[KmaApiHubRequestParam, ...]:
        """Return request parameters that are safe for model/user input."""
        return tuple(param for param in self.request_params if not param.is_credential)


def _snake(value: str) -> str:
    value = value.replace("2.0", "2_0")
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^A-Za-z0-9]+", "_", value)
    return value.strip("_").lower()


def _value_type(value: KmaApiHubScalar) -> Literal["string", "integer", "number", "boolean"]:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    return "string"


def _param(name: str, default: KmaApiHubScalar) -> KmaApiHubRequestParam:
    is_credential = name == "authKey"
    return KmaApiHubRequestParam(
        name=name,
        field_name=_snake(name),
        default=None if is_credential else default,
        value_type=_value_type(default),
        is_credential=is_credential,
    )


def _tool_id(service: str, operation: str) -> str:
    return f"kma_apihub_{_snake(service)}_{_snake(operation)}"


def _operation(
    category_seq: int,
    category_name_ko: str,
    service: str,
    operation: str,
    params: tuple[tuple[str, KmaApiHubScalar], ...],
    approval_state: KmaApiHubApprovalState = "approval_pending",
) -> KmaApiHubOperation:
    endpoint_path = f"/api/typ02/openApi/{service}/{operation}"
    return KmaApiHubOperation(
        category_seq=category_seq,
        category_name_ko=category_name_ko,
        service=service,
        operation=operation,
        tool_id=_tool_id(service, operation),
        endpoint_path=endpoint_path,
        request_params=tuple(_param(name, default) for name, default in params),
        approval_state=approval_state,
    )


KMA_APIHUB_STRUCTURED_OPERATIONS: tuple[KmaApiHubOperation, ...] = (
    _operation(
        14,
        "항공기상",
        "AmmIwxxmService",
        "getMetar",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "RKSI"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aappsAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "aep"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aappsArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "aep"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aclaAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "ca"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aclaArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "ca"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2acldAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "xml"),
            ("dateTime", "202011290000"),
            ("resultType", "cld"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2acldArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cld"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2adcoewAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cer"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2adcoewArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cer"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2afogAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "fog"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2afogArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "fog"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getEqkMsg",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20171101"),
            ("toTmFc", "20171129"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getEqkMsgList",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20171101"),
            ("toTmFc", "20171129"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getBuoy",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109120000 "),
            ("stnId", "1300001"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getSynop",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109120000 "),
            ("stnId", 1366),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getTemp",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109121200 "),
            ("stnId", "48839"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMLdapsUnisAll",
        (
            ("baseTime", "202603161500"),
            ("leadHour", 0),
            ("dataTypeCd", "temp"),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMLdapsUnisArea",
        (
            ("baseTime", "202603161500"),
            ("dataTypeCd", "Humi"),
            ("dataType", "XML"),
            ("dongCode", "1111051500"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMRdapsUnisAll",
        (
            ("baseTime", "202603161500"),
            ("leadHour", 0),
            ("dataTypeCd", "temp"),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMRdapsUnisArea",
        (
            ("baseTime", "202603161500"),
            ("dataTypeCd", "Humi"),
            ("dataType", "XML"),
            ("dongCode", "1111051500"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getLdapsUnisAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "202001140300"),
            ("leadHour", 1),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getLdapsUnisArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("dongCode", "1100000000"),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getRdapsUnisAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("leadHour", 0),
            ("dataTypeCd", "rain"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getRdapsUnisArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("dongCode", "1100000000"),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyBuoy",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "22101"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyLhaws",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 955),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyWaveBuoy",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "22441"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getObsOpenYear",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("month", "02"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getAirNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getDailyAirData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 92),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getDailyWthrData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 90),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getSfcStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getrAirStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("station", 128),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("station", 128),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo3",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 128),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getAvgTaAnamaly",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getRnAnamaly",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getSfcStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData3",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        8,
        "태풍",
        "SfcYearlyInfoService",
        "getTyphoonList",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getYearSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getYearSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getrAirStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getMaxWind",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getStdIsbrsfValue",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getTaHmLevel",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getUppLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getWindLevel",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getFcstVersion",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("ftype", "ODAM"),
            ("basedatetime", "202106280800"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getUltraSrtFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0630"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getUltraSrtNcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0600"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getVilageFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0500"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getLandFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "11A00101"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getSeaFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "12A20100"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getWthrSituation",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("stnId", 108),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getCompCappiQcdAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("compType", "CPP"),
            ("dataTypeCd", "CZ"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getCompCappiQcdArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("compType", "CPP"),
            ("dataTypeCd", "CZ"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aIrAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "087"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aIrArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "087"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aNrAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "013"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aNrArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "016"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aSwAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "038"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aSwArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "038"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aViAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "004"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aViArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "004"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aWvAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "063"),
            ("unitType", "lat"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aWvArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "063"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
    ),
)


def iter_structured_operations() -> tuple[KmaApiHubOperation, ...]:
    """Return all KMA APIHub structured operations in deterministic order."""
    return KMA_APIHUB_STRUCTURED_OPERATIONS


def get_operation_by_tool_id(tool_id: str) -> KmaApiHubOperation:
    """Return the KMA APIHub operation for *tool_id* or raise ``KeyError``."""
    for operation in KMA_APIHUB_STRUCTURED_OPERATIONS:
        if operation.tool_id == tool_id:
            return operation
    raise KeyError(tool_id)


def get_operation_by_id(operation_id: str) -> KmaApiHubOperation:
    """Return the KMA APIHub operation for ``<service>/<operation>``."""
    for operation in KMA_APIHUB_STRUCTURED_OPERATIONS:
        if operation.operation_id == operation_id:
            return operation
    raise KeyError(operation_id)
