# SPDX-License-Identifier: Apache-2.0
"""KMA APIHub structured OpenAPI operation catalog."""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

type KmaApiHubScalar = str | int | float | bool | None
type KmaApiHubApprovalState = Literal["approved", "approval_pending"]
type KmaApiHubAvailability = Literal[
    "active",
    "approval_pending",
    "retired",
    "upstream_unavailable",
]


class KmaApiHubRequestParam(BaseModel):
    """Official request parameter metadata for one KMA APIHub operation."""

    model_config = ConfigDict(frozen=True)

    name: str
    field_name: str
    required: bool = True
    default: KmaApiHubScalar = None
    value_type: Literal["string", "integer", "number", "boolean"] = "string"
    is_credential: bool = False


class KmaApiHubOperation(BaseModel):
    """One structured ``typ02/openApi`` operation exposed by KMA APIHub."""

    model_config = ConfigDict(frozen=True)

    category_seq: int
    category_name_ko: str
    service: str
    operation: str
    tool_id: str
    endpoint_path: str
    request_params: tuple[KmaApiHubRequestParam, ...]
    approval_state: KmaApiHubApprovalState = "approved"
    availability: KmaApiHubAvailability = "active"
    disabled_reason: str | None = None
    response_fields: tuple[str, ...] = Field(default_factory=tuple)

    @property
    def operation_id(self) -> str:
        """Return the stable APIHub ``<service>/<operation>`` identifier."""
        return f"{self.service}/{self.operation}"

    @property
    def non_credential_params(self) -> tuple[KmaApiHubRequestParam, ...]:
        """Return request parameters that are safe for model/user input."""
        return tuple(param for param in self.request_params if not param.is_credential)


def _snake(value: str) -> str:
    value = value.replace("2.0", "2_0")
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"[^A-Za-z0-9]+", "_", value)
    return value.strip("_").lower()


def _value_type(value: KmaApiHubScalar) -> Literal["string", "integer", "number", "boolean"]:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    return "string"


def _param(name: str, default: KmaApiHubScalar) -> KmaApiHubRequestParam:
    is_credential = name == "authKey"
    return KmaApiHubRequestParam(
        name=name,
        field_name=_snake(name),
        default=None if is_credential else default,
        value_type=_value_type(default),
        is_credential=is_credential,
    )


def _tool_id(service: str, operation: str) -> str:
    return f"kma_apihub_{_snake(service)}_{_snake(operation)}"


def _operation(
    category_seq: int,
    category_name_ko: str,
    service: str,
    operation: str,
    params: tuple[tuple[str, KmaApiHubScalar], ...],
    approval_state: KmaApiHubApprovalState = "approved",
    *,
    availability: KmaApiHubAvailability = "active",
    disabled_reason: str | None = None,
) -> KmaApiHubOperation:
    endpoint_path = f"/api/typ02/openApi/{service}/{operation}"
    return KmaApiHubOperation(
        category_seq=category_seq,
        category_name_ko=category_name_ko,
        service=service,
        operation=operation,
        tool_id=_tool_id(service, operation),
        endpoint_path=endpoint_path,
        request_params=tuple(_param(name, default) for name, default in params),
        approval_state=approval_state,
        availability=availability,
        disabled_reason=disabled_reason,
    )


KMA_APIHUB_STRUCTURED_OPERATIONS: tuple[KmaApiHubOperation, ...] = (
    _operation(
        14,
        "항공기상",
        "AmmIwxxmService",
        "getMetar",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "RKSI"),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct curl probes on 2026-05-26 returned resultCode=01 / "
            "APPLICATION_ERROR for RKSI, RKSS, and RKPK. Use the non-structured "
            "air_metar_dec.php URL operation for currently approved METAR "
            "decoded data until the structured IWXXM endpoint recovers."
        ),
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aappsAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "aep"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aappsArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "aep"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aclaAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "ca"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2aclaArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "ca"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2acldAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "xml"),
            ("dateTime", "202011290000"),
            ("resultType", "cld"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2acldArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cld"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2adcoewAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cer"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2adcoewArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "cer"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2afogAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "fog"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "CloudSatlitInfoService",
        "getGk2afogArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "202011290000"),
            ("resultType", "fog"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getEqkMsg",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20171101"),
            ("toTmFc", "20171129"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getEqkMsgList",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20171101"),
            ("toTmFc", "20171129"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getBuoy",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109120000 "),
            ("stnId", "1300001"),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct KMA APIHub probes on 2026-05-25 returned resultCode=02 "
            "DB_ERROR for this GTS operation, so it is not exposed as a "
            "callable adapter until KMA upstream behavior is stable."
        ),
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getSynop",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109120000 "),
            ("stnId", 47108),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct KMA APIHub probes on 2026-05-25 returned resultCode=02 "
            "DB_ERROR for this GTS operation, so it is not exposed as a "
            "callable adapter until KMA upstream behavior is stable."
        ),
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getTemp",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("tm", "202109121200 "),
            ("stnId", "48839"),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct KMA APIHub probes on 2026-05-25 returned resultCode=02 "
            "DB_ERROR for this GTS operation, so it is not exposed as a "
            "callable adapter until KMA upstream behavior is stable."
        ),
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMLdapsUnisAll",
        (
            ("baseTime", "202603161500"),
            ("leadHour", 0),
            ("dataTypeCd", "temp"),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMLdapsUnisArea",
        (
            ("baseTime", "202603161500"),
            ("dataTypeCd", "Humi"),
            ("dataType", "XML"),
            ("dongCode", "1111051500"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMRdapsUnisAll",
        (
            ("baseTime", "202603161500"),
            ("leadHour", 0),
            ("dataTypeCd", "temp"),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        9,
        "수치모델",
        "KIMModelInfoService",
        "getKIMRdapsUnisArea",
        (
            ("baseTime", "202603161500"),
            ("dataTypeCd", "Humi"),
            ("dataType", "XML"),
            ("dongCode", "1111051500"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getLdapsUnisAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "202001140300"),
            ("leadHour", 1),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approved",
        availability="retired",
        disabled_reason=(
            "Official KMA APIHub documentation marks UM model production as ended after "
            "2026-03-31; live probes return resultCode=99 for this operation."
        ),
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getLdapsUnisArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("dongCode", "1100000000"),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approved",
        availability="retired",
        disabled_reason=(
            "Official KMA APIHub documentation marks UM model production as ended after "
            "2026-03-31; live probes return resultCode=99 for this operation."
        ),
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getRdapsUnisAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("leadHour", 0),
            ("dataTypeCd", "rain"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
        availability="retired",
        disabled_reason=(
            "Official KMA APIHub documentation marks UM model production as ended after "
            "2026-03-31; live probes return resultCode=99 for this operation."
        ),
    ),
    _operation(
        9,
        "수치모델",
        "NwpModelInfoService",
        "getRdapsUnisArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("baseTime", "201911120300"),
            ("dongCode", "1100000000"),
            ("dataTypeCd", "Temp"),
            ("authKey", None),
        ),
        "approved",
        availability="retired",
        disabled_reason=(
            "Official KMA APIHub documentation marks UM model production as ended after "
            "2026-03-31; live probes return resultCode=99 for this operation."
        ),
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getBuoyMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyBuoy",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "22101"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyLhaws",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 955),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getDailyWaveBuoy",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "22441"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getLhawsMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getObsOpenYear",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("month", "02"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        3,
        "해양관측",
        "SeaMtlyInfoService",
        "getWaveBuoyMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getAirNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getDailyAirData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 92),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getDailyWthrData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 90),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getMmSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcMtlyInfoService",
        "getSfcStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcMtlyInfoService",
        "getrAirStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("station", 128),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2017),
            ("station", 128),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getAirStnInfo3",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 128),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getAvgTaAnamaly",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getRnAnamaly",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getSfcStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getStnPhnmnData3",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("station", 140),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        8,
        "태풍",
        "SfcYearlyInfoService",
        "getTyphoonList",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getYearSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        2,
        "지상관측",
        "SfcYearlyInfoService",
        "getYearSumry2",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "SfcYearlyInfoService",
        "getrAirStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getMaxWind",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getStdIsbrsfValue",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getTaHmLevel",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getUppLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        4,
        "고층관측",
        "UppMtlyInfoService",
        "getWindLevel",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", "47102"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getFcstVersion",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("ftype", "ODAM"),
            ("basedatetime", "202106280800"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getUltraSrtFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0630"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getUltraSrtNcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0600"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstInfoService_2.0",
        "getVilageFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 1000),
            ("dataType", "XML"),
            ("base_date", "20210628"),
            ("base_time", "0500"),
            ("nx", 55),
            ("ny", 127),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getLandFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "11A00101"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getSeaFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "12A20100"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        10,
        "예특보",
        "VilageFcstMsgService",
        "getWthrSituation",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("stnId", 108),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getCompCappiQcdAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("compType", "CPP"),
            ("dataTypeCd", "CZ"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getCompCappiQcdArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("compType", "CPP"),
            ("dataTypeCd", "CZ"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aIrAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "087"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aIrArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "087"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aNrAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "013"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aNrArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "016"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aSwAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "038"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aSwArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "038"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aViAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "004"),
            ("unitType", "R"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aViArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "004"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aWvAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "063"),
            ("unitType", "lat"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        6,
        "위성",
        "WthrSatlitInfoService",
        "getGk2aWvArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("waveType", "063"),
            ("unitType", "R"),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approved",
    ),
    _operation(
        14,
        "항공기상",
        "AftnAmmService",
        "getMetar",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "ZMUB"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AftnAmmService",
        "getSigmet",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "ZMUB"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AftnAmmService",
        "getTaf",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "ZMUB"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AirInfoService",
        "getAirInfo",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("fctm", "202109120000"),
            ("icaoCode", "RKJB"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AirPortService",
        "getAirPort",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("base_date", "20230425"),
            ("base_time", 1700),
            ("airPortCd", "RKSI"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmIwxxmService",
        "getAirmet",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmIwxxmService",
        "getSigmet",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmIwxxmService",
        "getTaf",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "RKSI"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmService",
        "getAirmet",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmService",
        "getSigmet",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmService",
        "getTaf",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("icao", "RKSI"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        14,
        "항공기상",
        "AmmService",
        "getWarning",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsMtlyInfoService",
        "getAwsStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsMtlyInfoService",
        "getDailyAwsData",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 129),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsMtlyInfoService",
        "getMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsMtlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsYearlyInfoService",
        "getAwsStnLstTbl",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsYearlyInfoService",
        "getNote",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsYearlyInfoService",
        "getStnbyMmSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("station", 96),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "AwsYearlyInfoService",
        "getYearSumry",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("year", 2016),
            ("month", "09"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getSunInfoBeach",
        (
            ("numOfRows", 1),
            ("pageNo", 10),
            ("dataType", "JSON"),
            ("Base_date", "20220501"),
            ("beach_num", 1),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getTideInfoBeach",
        (
            ("numOfRows", 1),
            ("pageNo", 10),
            ("dataType", "JSON"),
            ("base_date", "20220620"),
            ("beach_num", 1),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getTwBuoyBeach",
        (
            ("numOfRows", 1),
            ("pageNo", 10),
            ("dataType", "JSON"),
            ("beach_num", 1),
            ("searchTime", "202205011600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getUltraSrtFcstBeach",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "JSON"),
            ("base_date", "20220622"),
            ("base_time", 1230),
            ("beach_num", 1),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getVilageFcstBeach",
        (
            ("numOfRows", 1),
            ("pageNo", 10),
            ("dataType", "JSON"),
            ("base_date", "20220622"),
            ("base_time", 1100),
            ("beach_num", 1),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "BeachInfoservice",
        "getWhBuoyBeach",
        (
            ("numOfRows", 1),
            ("pageNo", 10),
            ("dataType", "JSON"),
            ("beach_num", 1),
            ("searchTime", "202205011600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getTsunamiMsg",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20081125"),
            ("toTmFc", "20151013"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        7,
        "지진/화산",
        "EqkInfoService",
        "getTsunamiMsgList",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("fromTmFc", "20081125"),
            ("toTmFc", "20151013"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "FcstZoneInfoService",
        "getFcstZoneCd",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "11A00101"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getDayStatistics",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("ST_YMD", "20161201"),
            ("ED_YMD", "20161201"),
            ("AREA_ID", "4122000000"),
            ("PA_CROP_SPE_ID", "PA130201"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getFmlandPwn",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("CURRENT_TM", "2019100516"),
            ("AREA_ID", "4122000000"),
            ("PA_CROP_SPE_ID", "PA130201"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getFmlandVilageFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("CURRENT_TM", "2016120102"),
            ("HOUR", 24),
            ("AREA_ID", "4122000000"),
            ("PA_CROP_SPE_ID", "PA130201"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getFmlandVilageNcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("CURRENT_TM", "2016120102"),
            ("AREA_ID", "4122000000"),
            ("PA_CROP_SPE_ID", "PA130201"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getMmStatistics",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("ST_YM", "201601"),
            ("ED_YM", "201601"),
            ("AREA_ID", "4211000000"),
            ("PA_CROP_SPE_ID", "PA020101"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FmlandWthrInfoService",
        "getPureStatistics",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("ST_YM", "201601"),
            ("ED_YM", "201601"),
            ("TDOM_CD", "DB005001"),
            ("AREA_ID", "4211000000"),
            ("PA_CROP_SPE_ID", "PA020101"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "FrstFcstInfoService",
        "getFrstOcurFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("BASE_DATE", "20170121"),
            ("BASE_TIME", "0500"),
            ("LAT", 36.5),
            ("LON", 128.0),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        12,
        "세계기상",
        "GtsInfoService",
        "getGtsStn",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("cc", 1001),
            ("category", "temp"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "HealthWthrIdxServiceV2",
        "getOakPollenRiskIdxV2",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "HealthWthrIdxServiceV2",
        "getPinePollenRiskIdxV2",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "HealthWthrIdxServiceV2",
        "getWeedsPollenRiskndxV2",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "LivingWthrIdxServiceV3",
        "getAirDiffusionIdxV3",
        (
            ("pageNo", 10),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "LivingWthrIdxServiceV3",
        "getSenTaIdxV3",
        (
            ("numOfRows", 10),
            ("pageNo", 1),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("requestCode", "A41"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "LivingWthrIdxServiceV3",
        "getUVIdxV3",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("areaNo", "1100000000"),
            ("time", "2021070618"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "MidFcstInfoService",
        "getMidFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("stnId", 108),
            ("tmFc", "201310170600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "MidFcstInfoService",
        "getMidLandFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "11B00000"),
            ("tmFc", "202107300600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "MidFcstInfoService",
        "getMidSeaFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "12A20000"),
            ("tmFc", "201404080600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "MidFcstInfoService",
        "getMidTa",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("regId", "11B10101"),
            ("tmFc", "201309030600"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "RoadWthrInfoService",
        "getCctvStnRoadWthr",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("eqmtId", "0500C00001"),
            ("hhCode", "00"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "RoadWthrInfoService",
        "getStdNodeLinkRoadWw",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("stdLinkId", "2370012300"),
            ("hhCode", "00"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "TourStnInfoService",
        "getCityTourClmIdx",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("CURRENT_DATE", "2018123110"),
            ("DAY", 3),
            ("CITY_AREA_ID", "5013000000"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        971,
        "융합기상",
        "TourStnInfoService",
        "getTourStnVilageFcst",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("CURRENT_DATE", "2019122010"),
            ("HOUR", 24),
            ("COURSE_ID", 1),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        5,
        "레이더",
        "WethrBasicInfoService",
        "getRadarObsStn",
        (
            ("pageNo", 1),
            ("numOfRows", 50),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        10,
        "예특보",
        "WethrBasicInfoService",
        "getWrnZoneCd",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("korName", ""),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        9,
        "수치모델",
        "WthrChartInfoService",
        "getAuxillaryChart",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("code1", "N500"),
            ("code2", "ANL"),
            ("time", "20151013"),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct curl probes on 2026-05-26 returned resultCode=99 for the "
            "documented and current analysis-chart request shape."
        ),
    ),
    _operation(
        9,
        "수치모델",
        "WthrChartInfoService",
        "getSurfaceChart",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("code", 24),
            ("time", "20151013"),
            ("authKey", None),
        ),
        "approved",
        availability="upstream_unavailable",
        disabled_reason=(
            "Direct curl probes on 2026-05-26 returned resultCode=99 for the "
            "documented and current analysis-chart request shape."
        ),
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getSiteCappiQcdAll",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("dataTypeCd", "DZ"),
            ("siteCode", "BRI"),
            ("sweep", 0),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        5,
        "레이더",
        "WthrRadarInfoService",
        "getSiteCappiQcdArea",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("dateTime", "201911120300"),
            ("dataTypeCd", "DZ"),
            ("siteCode", "BRI"),
            ("sweep", 0),
            ("dongCode", "1100000000"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "YdstInfoService",
        "getYdstObs",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "YdstInfoService",
        "getYdstSatlitImg",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("time", "202409060000"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
    _operation(
        2,
        "지상관측",
        "YdstInfoService",
        "getYdstSfcChart",
        (
            ("pageNo", 1),
            ("numOfRows", 10),
            ("dataType", "XML"),
            ("time", "202409050000"),
            ("authKey", None),
        ),
        "approval_pending",
        availability="approval_pending",
    ),
)


def iter_structured_operations(
    *,
    include_retired: bool = False,
) -> tuple[KmaApiHubOperation, ...]:
    """Return active KMA APIHub structured operations in deterministic order."""
    if include_retired:
        return KMA_APIHUB_STRUCTURED_OPERATIONS
    return tuple(
        operation
        for operation in KMA_APIHUB_STRUCTURED_OPERATIONS
        if operation.availability == "active"
    )


def get_operation_by_tool_id(tool_id: str) -> KmaApiHubOperation:
    """Return the KMA APIHub operation for *tool_id* or raise ``KeyError``."""
    for operation in KMA_APIHUB_STRUCTURED_OPERATIONS:
        if operation.tool_id == tool_id:
            return operation
    raise KeyError(tool_id)


def get_operation_by_id(operation_id: str) -> KmaApiHubOperation:
    """Return the KMA APIHub operation for ``<service>/<operation>``."""
    for operation in KMA_APIHUB_STRUCTURED_OPERATIONS:
        if operation.operation_id == operation_id:
            return operation
    raise KeyError(operation_id)
