#!/usr/bin/env bun
/**
 * gen-ipc-types.ts — IPC frame TypeScript type codegen
 *
 * Spawns the Python backend (via `uv run`) to extract the Pydantic v2
 * model_json_schema() for IPCFrame, writes the committed JSON Schema contract,
 * then feeds that schema to json-schema-to-typescript and writes
 * tui/src/ipc/frames.generated.ts.
 *
 * Usage:
 *   bun run scripts/gen-ipc-types.ts          # generate + write
 *   bun run scripts/gen-ipc-types.ts --check  # compare to committed file; exit 1 on drift
 *
 * FR-003: TypeScript types MUST be derived from Pydantic models, never hand-authored.
 */

import { compile } from "json-schema-to-typescript";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SCRIPT_DIR = import.meta.dir;
const TUI_ROOT = join(SCRIPT_DIR, "..");
const OUT_FILE = join(TUI_ROOT, "src", "ipc", "frames.generated.ts");
const OUT_SCHEMA_FILE = join(TUI_ROOT, "src", "ipc", "schema", "frame.schema.json");

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

const DO_NOT_EDIT_BANNER = `\
// ============================================================
// DO NOT EDIT — generated by tui/scripts/gen-ipc-types.ts
// Source of truth: src/ummaya/ipc/frame_schema.py (Pydantic v2)
// FR-003: TypeScript types are derived from Pydantic models.
// Regenerate: bun run gen:ipc
// Drift check: bun run gen:ipc -- --check
// ============================================================

/* eslint-disable */
// @ts-nocheck

`;

// ---------------------------------------------------------------------------
// Step 1: extract JSON Schema from Python
// ---------------------------------------------------------------------------

type ExtractedSchema = {
  schema: Record<string, unknown>;
  rawSchema: string;
};

async function extractSchemaFromPython(): Promise<ExtractedSchema> {
  const pySnippet = [
    "from ummaya.ipc.frame_schema import ipc_frame_json_schema",
    "import json, sys",
    "sys.stdout.write(json.dumps(ipc_frame_json_schema()))",
  ].join("; ");

  // Primary: uv run python -c
  let proc = Bun.spawn(["uv", "run", "python", "-c", pySnippet], {
    cwd: join(TUI_ROOT, ".."),
    stdout: "pipe",
    stderr: "pipe",
  });

  let exitCode = await proc.exited;
  let stdout = await new Response(proc.stdout).text();
  let stderr = await new Response(proc.stderr).text();

  if (exitCode !== 0) {
    // Fallback: python3 -m
    const fallbackProc = Bun.spawn(["python3", "-c", pySnippet], {
      cwd: join(TUI_ROOT, ".."),
      stdout: "pipe",
      stderr: "pipe",
    });
    exitCode = await fallbackProc.exited;
    stdout = await new Response(fallbackProc.stdout).text();
    stderr = await new Response(fallbackProc.stderr).text();
  }

  if (exitCode !== 0) {
    console.error("Python stderr:", stderr);
    throw new Error(
      `Failed to extract JSON Schema from Python (exit ${exitCode}): ${stderr}`
    );
  }

  try {
    return {
      schema: JSON.parse(stdout) as Record<string, unknown>,
      rawSchema: `${stdout}\n`,
    };
  } catch (e) {
    throw new Error(`Python output was not valid JSON: ${stdout.slice(0, 500)}`);
  }
}

// ---------------------------------------------------------------------------
// Step 2: compile JSON Schema → TypeScript
// ---------------------------------------------------------------------------

async function compileSchema(
  schema: Record<string, unknown>
): Promise<string> {
  const ts = await compile(schema as Parameters<typeof compile>[0], "IPCFrame", {
    bannerComment: "",
    style: {
      singleQuote: true,
      semi: true,
      tabWidth: 2,
      trailingComma: "es5",
      printWidth: 100,
    },
    additionalProperties: false,
    unknownAny: false,
    enableConstEnums: false,
    strictIndexSignatures: false,
    declareExternallyReferenced: true,
    $refOptions: {},
  });
  return DO_NOT_EDIT_BANNER + ts;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
const isCheck = args.includes("--check");

console.log("gen-ipc-types: extracting IPCFrame JSON Schema from Python...");
const { schema, rawSchema } = await extractSchemaFromPython();
const generatedSchema = rawSchema;

const discriminatorKeys = Object.keys(
  (schema as any)?.discriminator?.mapping ?? {}
);
console.log(`gen-ipc-types: found ${discriminatorKeys.length} discriminator arms: ${discriminatorKeys.join(", ")}`);

console.log("gen-ipc-types: compiling schema to TypeScript...");
const generated = await compileSchema(schema);

if (isCheck) {
  // --check mode: compare against committed file
  let committed: string;
  let committedSchema: string;
  try {
    committed = readFileSync(OUT_FILE, "utf-8");
    committedSchema = readFileSync(OUT_SCHEMA_FILE, "utf-8");
  } catch {
    console.error(
      `gen-ipc-types --check: committed file not found at ${OUT_FILE} or ${OUT_SCHEMA_FILE}`
    );
    console.error("Run: bun run gen:ipc to generate it first.");
    process.exit(1);
  }

  if (generated === committed && generatedSchema === committedSchema) {
    console.log("gen-ipc-types --check: OK — generated files match committed files.");
    process.exit(0);
  } else {
    // Write temp file for diff inspection
    const tmp = join(tmpdir(), `frames.generated.ts.new`);
    writeFileSync(tmp, generated, "utf-8");
    console.error(
      `gen-ipc-types --check: DRIFT DETECTED — committed IPC generated files differ from live schema.`
    );
    console.error(`  New output written to: ${tmp}`);
    console.error("  Run: bun run gen:ipc to update the committed file.");
    process.exit(1);
  }
} else {
  // Write mode
  mkdirSync(join(TUI_ROOT, "src", "ipc"), { recursive: true });
  mkdirSync(join(TUI_ROOT, "src", "ipc", "schema"), { recursive: true });
  writeFileSync(OUT_SCHEMA_FILE, generatedSchema, "utf-8");
  writeFileSync(OUT_FILE, generated, "utf-8");
  console.log(`gen-ipc-types: written ${OUT_SCHEMA_FILE}`);
  console.log(`gen-ipc-types: written ${OUT_FILE}`);
  process.exit(0);
}
