#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# audit-prod § Audit 2 — 20 Mock adapters × 5 verification axes (100 cells)
#
# Wraps audit-2-mock.py + collects frontend grep evidence for the
# UI/UX disclaimer audit (axis V5 follow-up).
#
# Mock adapter inventory (ground-truth count is 20, not 25 as the
# spec request guessed):
#   Lookup × 2:
#     mock_lookup_module_gov24_certificate
#     mock_lookup_module_hometax_simplified
#   Submit × 5:
#     mock_submit_module_gov24_minwon
#     mock_submit_module_hometax_taxreturn
#     mock_submit_module_public_mydata_action
#     mock_traffic_fine_pay_v1
#     mock_welfare_application_submit_v1
#   Verify × 10:
#     mock_verify_gongdong_injeungseo
#     mock_verify_geumyung_injeungseo
#     mock_verify_ganpyeon_injeung
#     mock_verify_mobile_id
#     mock_verify_mydata
#     mock_verify_module_simple_auth
#     mock_verify_module_modid
#     mock_verify_module_kec
#     mock_verify_module_geumyung
#     mock_verify_module_any_id_sso
#   Subscribe × 3:
#     mock_cbs_disaster_v1
#     mock_rss_public_notices_v1
#     mock_rest_pull_tick_v1
#
# Verification axes (all 5 evaluated for every adapter):
#   V1 envelope_shape       — primitive output keys + kind hints
#   V2 transparency_stamp   — six _mode/_reference_implementation fields
#   V3 canonical_map        — verify only — system_v1.md <verify_families>
#   V4 discovery_hint       — BM25 hit ranks adapter ≤ 10 for civic probe
#   V5 citizen_disclaimer   — _mode=mock surfaces in adapter output
#
# Bash wrapper additionally greps the TUI side-effect renderers for mock-mode
# disclaimer rendering (UI/UX axis #6 — "시민 mis-info risk").

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

cd "$REPO_ROOT"

OUT_DIR="$SCRIPT_DIR"
LOG_FILE="${KOSMOS_BACKEND_LOG_FILE:-/tmp/audit-2.log}"

echo "=== Audit 2 — 20 Mock × 5 axes ==="
echo "repo_root  = $REPO_ROOT"
echo "log_file   = $LOG_FILE"
echo

# -----------------------------------------------------------------------------
# Stage 1 — backend matrix (Python: imports registry + invokes adapters)
# -----------------------------------------------------------------------------

echo "--- Stage 1: backend matrix (audit-2-mock.py) ---"
KOSMOS_BACKEND_LOG_FILE="$LOG_FILE" \
  uv run python "$SCRIPT_DIR/audit-2-mock.py" \
  | tee "$OUT_DIR/audit-2-mock-output.txt"

cp -f /tmp/audit-2-mock-matrix.json "$OUT_DIR/audit-2-mock-matrix.json"
echo

# -----------------------------------------------------------------------------
# Stage 2 — frontend wiring grep audit (TUI primitive renderers)
# -----------------------------------------------------------------------------

echo "--- Stage 2: TUI wiring grep audit ---"

GREP_OUT="$OUT_DIR/audit-2-mock-tui-wiring.txt"
{
  echo "# Audit 2 — TUI wiring grep audit"
  echo "# Generated by audit-2-mock.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo

  echo "## Q1: VerifyPrimitive renders backend status -> citizen Korean label?"
  grep -n "verified\|인증 완료\|인증 실패\|인증 처리 중" \
    tui/src/tools/VerifyPrimitive/VerifyPrimitive.ts || echo "  (no hit)"
  echo

  echo "## Q2: SubmitPrimitive renders adapter_receipt -> Korean status label?"
  grep -n "transaction_id\|접수 번호\|제출이 접수\|반려" \
    tui/src/tools/SubmitPrimitive/SubmitPrimitive.ts || echo "  (no hit)"
  echo

  echo "## Q3: SubscribePrimitive renders handle_id -> citizen acknowledgment?"
  grep -n "handle_id\|구독 완료\|실시간 스트림" \
    tui/src/tools/SubscribePrimitive/SubscribePrimitive.ts || echo "  (no hit)"
  echo

  echo "## Q4: TUI surfaces mock disclaimer (_mode==='mock' / 🧪 / 모의 응답)?"
  echo "  Backend stamps _mode='mock' on every adapter output; frontend MUST"
  echo "  render it so the citizen does not mistake mock invocation for a real"
  echo "  agency action ('신청됐다' / '인증됐다' mis-info)."
  echo
  echo "### grep _mode/mock disclaimer in TUI primitive renderers:"
  grep -rn "_mode\|🧪\|모의\|mock disclaimer" \
    tui/src/tools/VerifyPrimitive/ \
    tui/src/tools/SubmitPrimitive/ \
    tui/src/tools/SubscribePrimitive/ \
    tui/src/tools/LookupPrimitive/ \
    || echo "  (no hits — FAIL: mock disclaimer not rendered to citizen)"
  echo
  echo "### grep source_mode handling (MOCK vs LIVE vs INTERNAL branches):"
  grep -rn "source_mode" \
    tui/src/tools/VerifyPrimitive/ \
    tui/src/tools/SubmitPrimitive/ \
    tui/src/tools/SubscribePrimitive/ \
    || echo "  (no hits)"
  echo

  echo "## Q5: /consent list and /agents surface mock receipts as mock?"
  grep -rn "_mode\|mock\b" \
    tui/src/components/consent/ \
    tui/src/commands/consent.ts \
    tui/src/commands/agents.ts \
    2>/dev/null || echo "  (no hits — investigate /consent and /agents commands)"
  echo

  echo "## Q6: System prompt teaches LLM to caveat mock results to citizen?"
  grep -n "_mode\|mock\b\|모의\|시연용\|fixture" prompts/system_v1.md \
    || echo "  (no hits — system prompt does not instruct mock caveat)"
  echo
} > "$GREP_OUT"

cat "$GREP_OUT" | head -120
echo
echo "Full grep audit -> $GREP_OUT"
echo
echo "=== Audit 2 DONE ==="
