# SPDX-License-Identifier: Apache-2.0
"""Public AX document harness package."""

from ummaya.tools.documents.adapter_registry import (
    DocumentAdapterRegistry,
    EngineBackedDocumentAdapter,
    UnsupportedDocumentAdapterError,
    build_default_document_adapter_registry,
    build_document_adapter_registry_from_engine_registry,
)
from ummaya.tools.documents.artifact_store import (
    ArtifactStoreConflictError,
    ArtifactStoreError,
    ArtifactStoreSecurityError,
    DocumentArtifactStore,
)
from ummaya.tools.documents.baselines import (
    CONFORMANCE_BASELINE_FIXTURE_PATH,
    BaselineField,
    BaselineTableGeometry,
    BaselineTextAnchor,
    ConformanceBaseline,
    ConformanceBaselineCatalog,
    load_conformance_baselines,
)
from ummaya.tools.documents.capability import (
    FormatCapabilityProfile as CandidateCapabilityProfile,
)
from ummaya.tools.documents.capability import (
    PromotionDecision,
    PromotionDecisionManifest,
    PromotionDecisionRecord,
    build_inspection_read_profile,
    evaluate_capability_promotion,
    load_promotion_decision_manifest,
    persist_promotion_decision_manifest,
)
from ummaya.tools.documents.contracts import (
    DocumentToolContract,
    DocumentToolContractCatalog,
    load_document_tool_contracts,
)
from ummaya.tools.documents.diff import DocumentChange, DocumentDiff, RenderArtifactRecord
from ummaya.tools.documents.engines import (
    DocumentEngineRegistry,
    DocumentInspectionEngine,
    DocumentMutationEngine,
    UnsupportedDocumentEngineError,
    build_default_document_engine_registry,
)
from ummaya.tools.documents.fixtures import (
    DocumentFixtureManifest,
    load_fixture_manifest,
)
from ummaya.tools.documents.formats.base import DocumentFormatAdapter
from ummaya.tools.documents.inspection import inspect_document
from ummaya.tools.documents.intake import (
    DocumentIntakePolicy,
    inspect_document_intake,
)
from ummaya.tools.documents.models import (
    KNOWN_DOCUMENT_FORMAT_FAMILIES,
    PROMOTED_RUNTIME_DOCUMENT_FORMATS,
    ArtifactLineage,
    AutonomousFillPlan,
    AutonomousSaveIntent,
    AutonomousStyleIntent,
    BlockedReason,
    DocumentArtifact,
    DocumentChangedViewport,
    DocumentClipRect,
    DocumentExtraction,
    DocumentFormat,
    DocumentFormatFamily,
    DocumentIntakeResult,
    DocumentIntent,
    DocumentIR,
    DocumentPatch,
    DocumentPatchOperation,
    DocumentProtectedRange,
    DocumentSavedExport,
    DocumentSecurityFinding,
    DocumentToolCall,
    DocumentToolResult,
    DocumentViewportCamera,
    FormatCapabilityProfile,
    FormField,
    FormSlot,
    KnownDocumentFormat,
    OperationType,
    PermissionState,
    PrimitiveName,
    PromotionCapability,
    PromotionGateResult,
    PromotionState,
    ProtectedRangeCategory,
    PublicFormValidationReport,
    SecurityState,
    SourceAnchor,
    StyleDescriptor,
    ToolResultStatus,
    ValidationDecision,
    ValidationFinding,
    ValidationReadiness,
)
from ummaya.tools.documents.orchestrator import (
    DocumentInspectionOrchestrator,
    DocumentOrchestrator,
)
from ummaya.tools.documents.patch import (
    DocumentPatchResult,
    apply_document_patch,
    copy_for_edit,
)
from ummaya.tools.documents.permissions import (
    DocumentArtifactPermissionKind,
    DocumentArtifactPermissionPayload,
    build_document_artifact_permission,
    document_permission_denied_result,
)
from ummaya.tools.documents.planner import plan_autonomous_fill, public_document_writing_profile
from ummaya.tools.documents.registry import (
    DOCUMENT_TOOL_IDS,
    DocumentToolRuntime,
    register_document_tools,
)
from ummaya.tools.documents.render import (
    DocumentRenderResult,
    render_document_evidence,
)
from ummaya.tools.documents.reread import (
    DocumentReReadResult,
    ReReadMismatch,
    reread_derivative,
)
from ummaya.tools.documents.scorecard import (
    CapabilityScorecard,
    PublicFormMetricScore,
    compute_public_form_metrics,
)
from ummaya.tools.documents.style import (
    DocumentPatchValidationError,
    validate_document_patch,
)
from ummaya.tools.documents.tool_defs import (
    DocumentApplyFillRequest,
    DocumentApplyStyleRequest,
    DocumentCopyForEditRequest,
    DocumentExtractionResult,
    DocumentExtractRequest,
    DocumentFieldPatch,
    DocumentFormSchemaRequest,
    DocumentInspectRequest,
    DocumentInspectResult,
    DocumentLocator,
    DocumentMutationResult,
    DocumentRenderRequest,
    DocumentSaveRequest,
    DocumentStylePatch,
    DocumentValidatePublicFormRequest,
    DocumentValidationResult,
    build_document_tool_definitions,
    needs_input_document_tool_result,
    unsupported_document_tool_result,
)
from ummaya.tools.documents.validate import validate_public_form

__all__ = [
    "DOCUMENT_TOOL_IDS",
    "ArtifactLineage",
    "ArtifactStoreConflictError",
    "ArtifactStoreError",
    "ArtifactStoreSecurityError",
    "AutonomousFillPlan",
    "AutonomousSaveIntent",
    "AutonomousStyleIntent",
    "BlockedReason",
    "BaselineField",
    "BaselineTableGeometry",
    "BaselineTextAnchor",
    "CONFORMANCE_BASELINE_FIXTURE_PATH",
    "CandidateCapabilityProfile",
    "CapabilityScorecard",
    "ConformanceBaseline",
    "ConformanceBaselineCatalog",
    "DocumentArtifact",
    "DocumentArtifactPermissionKind",
    "DocumentArtifactPermissionPayload",
    "DocumentArtifactStore",
    "DocumentAdapterRegistry",
    "DocumentApplyFillRequest",
    "DocumentApplyStyleRequest",
    "DocumentChangedViewport",
    "DocumentClipRect",
    "DocumentCopyForEditRequest",
    "DocumentEngineRegistry",
    "DocumentExtractRequest",
    "DocumentExtraction",
    "DocumentExtractionResult",
    "DocumentFieldPatch",
    "DocumentFixtureManifest",
    "DocumentFormat",
    "DocumentFormatAdapter",
    "DocumentFormatFamily",
    "DocumentIR",
    "DocumentFormSchemaRequest",
    "DocumentIntakePolicy",
    "DocumentIntakeResult",
    "DocumentIntent",
    "DocumentInspectRequest",
    "DocumentInspectResult",
    "DocumentInspectionEngine",
    "DocumentInspectionOrchestrator",
    "DocumentLocator",
    "DocumentMutationEngine",
    "DocumentMutationResult",
    "DocumentOrchestrator",
    "DocumentPatch",
    "DocumentPatchResult",
    "DocumentPatchOperation",
    "DocumentPatchValidationError",
    "DocumentProtectedRange",
    "DocumentReReadResult",
    "DocumentRenderResult",
    "DocumentRenderRequest",
    "DocumentSaveRequest",
    "DocumentSavedExport",
    "DocumentSecurityFinding",
    "DocumentStylePatch",
    "DocumentToolCall",
    "DocumentToolContract",
    "DocumentToolContractCatalog",
    "DocumentToolResult",
    "DocumentToolRuntime",
    "DocumentViewportCamera",
    "DocumentValidationResult",
    "DocumentValidatePublicFormRequest",
    "DocumentChange",
    "DocumentDiff",
    "EngineBackedDocumentAdapter",
    "FormatCapabilityProfile",
    "FormField",
    "FormSlot",
    "KNOWN_DOCUMENT_FORMAT_FAMILIES",
    "KnownDocumentFormat",
    "OperationType",
    "PermissionState",
    "PrimitiveName",
    "ProtectedRangeCategory",
    "PROMOTED_RUNTIME_DOCUMENT_FORMATS",
    "PromotionCapability",
    "PromotionDecision",
    "PromotionDecisionManifest",
    "PromotionDecisionRecord",
    "PromotionGateResult",
    "PromotionState",
    "PublicFormValidationReport",
    "PublicFormMetricScore",
    "ReReadMismatch",
    "RenderArtifactRecord",
    "SecurityState",
    "SourceAnchor",
    "StyleDescriptor",
    "ToolResultStatus",
    "UnsupportedDocumentAdapterError",
    "UnsupportedDocumentEngineError",
    "build_document_adapter_registry_from_engine_registry",
    "build_default_document_adapter_registry",
    "build_default_document_engine_registry",
    "ValidationDecision",
    "ValidationFinding",
    "ValidationReadiness",
    "apply_document_patch",
    "build_document_artifact_permission",
    "build_document_tool_definitions",
    "build_inspection_read_profile",
    "copy_for_edit",
    "compute_public_form_metrics",
    "document_permission_denied_result",
    "evaluate_capability_promotion",
    "inspect_document_intake",
    "inspect_document",
    "load_document_tool_contracts",
    "load_fixture_manifest",
    "load_conformance_baselines",
    "load_promotion_decision_manifest",
    "needs_input_document_tool_result",
    "plan_autonomous_fill",
    "public_document_writing_profile",
    "persist_promotion_decision_manifest",
    "register_document_tools",
    "render_document_evidence",
    "reread_derivative",
    "unsupported_document_tool_result",
    "validate_document_patch",
    "validate_public_form",
]
